### ISSUE TITLE
Parsing of csv file does not work in Linux

### ISSUE THREAD

**Issue by mpulukkinen** [mpulukkinen/CsvPowerTemperature#1]
[13:33:38 ERR] Unhandled exception
System.AggregateException: One or more errors occurred. (Input string was not in a correct format.)
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at CsvPowerToTemp.PowerReadingProviders.ReadFromCsvFilesInCurrentFolder.GetPowerReadings(String[] args)
   at CsvPowerToTemp.Program.<>c__DisplayClass4_0.<<Main>b__1>d.MoveNext() in /home/runner/work/CsvPowerTemperature/CsvPowerTemperature/Program.cs:line 48

Probably caused by cultural  environment values (float)

**Comment by mpulukkinen** [comment]
Note to self: use Path.GetFileName(file).Split("_"); because the file name may contain the whole path

**Comment by mpulukkinen** [comment]
Actual root cause: "_" if the path mixed up the year parsing from file name...
